### PR TITLE
UEK-NEXT support

### PR DESCRIPTION
**Pull request by brenns10**
This pull request begins running the Github CI tests against UEK-next, which is currently at 6.11. It includes a whole crop of fixes to helpers that allow the tests to pass. This is the first version of UEK-next that I'm actually doing this for, so it includes a lot of changes from UEK7 era up till the present.

These fixes are are necessary, but almost certainly incomplete. The Github CI tests are very small QEMU VMs, and I did manually verify that the tests pass against my laptop as well. There are plenty of subsystems not exercised by my laptop or the limited VM in the CI tests.

I'm breaking these changes down into a few categories for which I believe subject matter experts should review. If you're tagged here, please take a look at the subset of changes mentioned (note the Git SHAs may not be correct, as I may need to amend things to add bug references).

```
# SMP, workqueue: @imran-kn 
648a271 smp: skip test on live systems
8ded078 workqueue: handle changes in 6.9

# Virtual Filesystem / mounts: @gtmoth 
2d3ffc8 mounts: include superblock sub-type
0cf7aeb fsnotify: handle changes in 6.10
7bf4632 dentry: mark dentry_path_any_mount for removal

# Block IO: @biger410
32d3d64 partition: add tests for partition info
faa81ff partition: use block fixes for 6.10
9c5f640 block: fixes for v6.10
0f893d0 nvme: fixes for Linux 6.11

# Memory management: @jianfenw 
ef72437 numastat: Add missing stats from newer kernels
2e5bc1f task: support computing rss_stat for v6.2+

# Internals & tiny, obviously correct changes: @brenns10 
99bf206 bt: eliminate TODO for DWARF opcode exceptions
ea84304 module: remove compatibility with drgn < 0.0.21
a78f4b0 testing: litevm: enable testing on uek-next
2bb9b08 net: use task_cpu() helper

# Scheduling & generic kernel: @imran-kn or @biger410 
c86272c Fix for_each_task_in_group() for Linux 6.7+
18081d1 tests: task: fix failure on v6.9
c0dd25e module: support v6.4+ & efficient address lookup

# Generic driver APIs: @biger410 as a reviewer of last resort
afdf8d4 device: add helpers to get subsys_private
```

### CODE REVIEW

**Review by biger410 — COMMENTED** [review]
IO fixes looks good to me

**Review by gtmoth — APPROVED** [review]

**Review by gtmoth — APPROVED** [review]

**Review by imran-kn — COMMENTED** [review]
Changes, in following files, LGTM:

1. test_mm.py
2. test_module.py
3. test_smp.py
4. test_task.py
5. module.py
6. task.py
7. workqueue.py
8. numastat.py

**Review by imran-kn — COMMENTED** [review]
Changes in lsmod.py are good to go.

**Review by jianfenw — APPROVED** [review]
LGTM. Looks like the upstream has made quite some changes in mm.
Thanks for fixing these!

**Review by biger410 — APPROVED** [review]

**Pull request merged**
